job_family: [
  "accountant", 
  "data analyst", 
  "data engineer", 
  "electrical engineer",
  "software enigneer", 
]
experience_level: [
  "junior-level",
  "senior-level"
]

definitions_loc:
  experience_level: ["data","definitions","experience_level.txt"]
  job_family: ["data","definitions","job_family.txt"]